[tool.black]
line-length = 88
skip-string-normalization = false
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 88
combine_as_imports = true
force_single_line = true
remove_redundant_aliases = true
known_third_party = [
    "numpy",
    "pandas",
    "requests"
]
skip = [
    ".git",
    ".tox",
    ".venv",
    "build",
    "dist"
]